[project]
name = "deployment-builder"
version = "0.1.0"
description = ""
authors = [
    {name = "Jim Fitzpatrick",email = "jimfity@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.0.0",
    "pyyaml>=6.0",
    "tomli>=2.0.0",
]

[tool.poetry.group.dev.dependencies]
black = "^24.0.0"
pytest = "^8.0.0"

[tool.poetry]
packages = [{include = "deployment_builder", from = "src"}]
scripts = {deploy = "deployment_builder.cli:cli"}

[tool.black]
line-length = 120
target-version = ['py313']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
